# Generated by Django 3.0.4 on 2020-05-31 22:10

import apps.periodico.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='periodico.CategoriaNoticia')),
            ],
            options={
                'verbose_name': 'categoria noticia',
                'verbose_name_plural': 'categorias noticias',
                'db_table': 'CATEGORIA_NOTICIA',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ingrese el Titulo de la Noticia', max_length=200)),
                ('sub_titulo', models.CharField(help_text='Ingrese un subtitulo', max_length=255)),
                ('descripcion', models.TextField(help_text='Ingrese la descripcion')),
                ('link_fuente', models.URLField(blank=True, help_text='Ingrese la url de la fuente de la noticia')),
                ('localidad', models.CharField(blank=True, help_text='Lugar de la Noticia', max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ManyToManyField(to='periodico.CategoriaNoticia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'db_table': 'NOTICIA',
            },
        ),
        migrations.CreateModel(
            name='FotoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='El tamaño maximo para las fotos es 3 Megas', upload_to='noticias/', validators=[apps.periodico.validators.tamaño_del_archivo])),
                ('descripcion', models.CharField(help_text='Ingrese breve descripcion de la foto', max_length=150)),
                ('autor', models.CharField(help_text='Ingrese el autor de la foto', max_length=50)),
                ('localidad', models.CharField(help_text='Ingrese la localidad de la foto', max_length=20)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodico.Noticia')),
            ],
            options={
                'verbose_name': 'foto noticia',
                'verbose_name_plural': 'foto noticias',
                'db_table': 'FOTO_NOTICIA',
            },
        ),
    ]
