# Generated by Django 3.0.4 on 2020-05-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorianoticia',
            options={'verbose_name': 'categoria noticia', 'verbose_name_plural': '10. Categorias Noticias'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'noticia', 'verbose_name_plural': '11. Noticias'},
        ),
    ]
