# Generated by Django 3.0.4 on 2020-05-31 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al Sitio Administrativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activar usuario')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombres', models.CharField(blank=True, max_length=40, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=40, verbose_name='Apellidos')),
                ('token_firebase', models.CharField(blank=True, max_length=255, null=True, verbose_name='TokenFirebase')),
                ('foto', models.ImageField(blank=True, default='perfiles/no-img.jpg', null=True, upload_to='perfiles/')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'db_table': 'CIUDAD',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('calificacion', models.IntegerField(default=0)),
                ('disponibilidad', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado'), ('N', 'No Disponible')], default='N', max_length=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'db_table': 'PERFIL',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'db_table': 'HORARIO',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autenticacion.Ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='USUARIO_GRUPO', help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos otorgados a cada uno de sus grupos.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='grupos1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='USUARIO_PERMISO', help_text='Permisos específicos para este usuario.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
