# Generated by Django 3.0.4 on 2020-05-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'ciudad', 'verbose_name_plural': '2. Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': '1. Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/no-img.jpg', null=True, upload_to='usuarios/'),
        ),
    ]
