# Generated by Django 3.0.4 on 2020-06-03 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_auto_20200603_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargadociudad',
            name='ciudad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.Ciudad'),
        ),
    ]
