# Generated by Django 3.0.4 on 2020-06-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_auto_20200603_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='costo_min',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='Costo minimo de un envio en Bs.', max_digits=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TarifaCostoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicial', models.DecimalField(decimal_places=1, max_digits=7)),
                ('costo', models.DecimalField(decimal_places=1, max_digits=7)),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.Ciudad')),
            ],
            options={
                'verbose_name': 'Tarifa del Costo del Envio',
                'verbose_name_plural': 'Tarifas de los Costos de Envio',
                'db_table': 'TARIFA_COSTO_ENVIO',
            },
        ),
    ]
