# Generated by Django 3.0.4 on 2020-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_auto_20200604_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cant_calificacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
