# Generated by Django 3.0.4 on 2020-06-09 02:21

import apps.autenticacion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0011_auto_20200608_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[apps.autenticacion.validators.validar_porcentaje], verbose_name='Comision'),
        ),
    ]
