# Generated by Django 3.0.4 on 2020-06-09 02:39

import apps.autenticacion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0013_auto_20200608_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=1, default=0, help_text='el valor es un porcentaje', max_digits=4, validators=[apps.autenticacion.validators.validar_porcentaje], verbose_name='Comision'),
        ),
    ]
