# Generated by Django 3.0.4 on 2020-06-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0015_auto_20200614_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_register',
            field=models.BooleanField(default=False, verbose_name='Registrado'),
        ),
    ]
