# Generated by Django 3.0.4 on 2020-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0016_usuario_is_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionesandroidapp',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
