# Generated by Django 3.0.4 on 2020-07-10 09:59

import apps.autenticacion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0018_versionesandroidapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='radio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='El radio del area, valor decimal debe estar en km', max_digits=6),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Valor(en json, latitud,longitud) que determina el centro del area, los pedidos que se encuentren dentro de esta area seran aceptados, de lo contrario no.', max_length=255, validators=[apps.autenticacion.validators.validate_latitude_longitude]),
        ),
    ]
