# Generated by Django 3.0.4 on 2020-05-31 22:10

import apps.empresa.validators
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria_empresa',
                'verbose_name_plural': 'Categorias de una Empresa',
                'db_table': 'CATEGORIA_EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.CategoriaProducto')),
            ],
            options={
                'verbose_name': 'categoria producto',
                'verbose_name_plural': 'categorias producto',
                'db_table': 'CATEGORIA_ARTICULO',
            },
        ),
        migrations.CreateModel(
            name='ChatProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'chat producto',
                'verbose_name_plural': 'chat productos',
                'db_table': 'CHAT_PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.CategoriaEmpresa')),
                ('empresario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='asd')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('E', 'En Curso'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='N', max_length=1)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Zona')),
                ('telefono', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('hora_inicio', models.TimeField(blank=True, default='15:00:00')),
                ('hora_fin', models.TimeField(blank=True, default='15:00:00')),
                ('disponible', models.BooleanField(blank=True, default=False)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('foto', models.ImageField(blank=True, help_text='El tamaño maximo para las fotos es 3 Megas', null=True, upload_to='sucursal/', validators=[apps.empresa.validators.tamaño_del_archivo])),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='autenticacion.Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'SUCURSAL',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=1, max_digits=7)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('is_combo', models.BooleanField(default=False)),
                ('atributos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.CategoriaProducto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Sucursal')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[apps.empresa.validators.cantidad_min_value, apps.empresa.validators.cantidad_max_value])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Pedido')),
                ('producto_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Producto')),
            ],
            options={
                'verbose_name': 'pedido_producto',
                'verbose_name_plural': 'pedido_productos',
                'db_table': 'PEDIDO_PRODUCTO',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Sucursal'),
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_propietario', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.ChatProducto')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'db_table': 'MENSAJE_CHAT',
            },
        ),
        migrations.CreateModel(
            name='FotoSucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='El tamaño maximo para las fotos es 3 Megas', upload_to='sucursal/', validators=[apps.empresa.validators.tamaño_del_archivo])),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='empresa.Sucursal')),
            ],
            options={
                'verbose_name': 'foto tienda',
                'verbose_name_plural': 'fotos tienda',
                'db_table': 'FOTO_TIENDA',
            },
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='El tamaño maximo para las fotos es 3 Megas', null=True, upload_to='productos/', validators=[apps.empresa.validators.tamaño_del_archivo])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Producto')),
            ],
            options={
                'verbose_name': 'foto producto',
                'verbose_name_plural': 'fotos productos',
                'db_table': 'FOTO_PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'db_table': 'FAVORITO',
            },
        ),
        migrations.AddField(
            model_name='chatproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Producto'),
        ),
        migrations.AddField(
            model_name='chatproducto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chat_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=14)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Pedido')),
            ],
            options={
                'verbose_name': 'chat_pedido',
                'verbose_name_plural': 'chat_pedidos',
                'db_table': 'CHAT_PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, validators=[apps.empresa.validators.cantidad_min_value, apps.empresa.validators.cantidad_max_value])),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo', to='empresa.Producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto', to='empresa.Producto')),
            ],
            options={
                'verbose_name': 'combo',
                'verbose_name_plural': 'combos',
                'db_table': 'COMBO',
                'unique_together': {('combo', 'producto')},
            },
        ),
    ]
