# Generated by Django 3.0.4 on 2020-05-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaempresa',
            options={'verbose_name': 'categoria_empresa', 'verbose_name_plural': '4. Categorias de una Empresa'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'categoria producto', 'verbose_name_plural': '7. Categorias de un Producto'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'empresa', 'verbose_name_plural': '5. Empresas'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'pedido', 'verbose_name_plural': '9. Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': '8. Productos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': '6. Sucursales'},
        ),
    ]
