# Generated by Django 3.0.4 on 2020-06-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20200531_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=7, verbose_name='costo de envio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_final',
            field=models.DecimalField(decimal_places=1, default=22.0, max_digits=7, verbose_name='precio final'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Monto Total de productos'),
        ),
    ]
