# Generated by Django 3.0.4 on 2020-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20200603_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(default=(-21.5024185, -64.7341385), max_length=255, verbose_name='Ubicacion'),
            preserve_default=False,
        ),
    ]
