# Generated by Django 3.0.4 on 2020-06-04 07:10

import apps.empresa.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20200603_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[apps.empresa.validators.validate_latitude_longitude]),
        ),
    ]
