# Generated by Django 3.0.4 on 2020-06-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20200604_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaempresa',
            options={'verbose_name': 'categoria empresa', 'verbose_name_plural': '4. Categorias Empresa'},
        ),
    ]
