# Generated by Django 3.0.4 on 2020-06-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20200606_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='encargado',
        ),
    ]
