# Generated by Django 3.0.4 on 2020-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_remove_sucursal_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_calificado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='is_calificado_empresario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='is_calificado_repartidor',
            field=models.BooleanField(default=False),
        ),
    ]
