# Generated by Django 3.0.4 on 2020-06-11 08:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0011_auto_20200608_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 11, 4, 35, 5, 79244)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'producto')},
        ),
    ]
