# Generated by Django 3.0.4 on 2020-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_auto_20200611_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='combo_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_activos',
            field=models.CharField(default='1111111', max_length=7),
        ),
    ]
