# Generated by Django 3.0.4 on 2020-06-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_auto_20200612_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='combo_activo',
            field=models.BooleanField(default=True),
        ),
    ]
