# Generated by Django 3.0.4 on 2020-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_rankingproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_calificacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
