# Generated by Django 3.0.4 on 2020-06-16 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_auto_20200614_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresa.CategoriaProducto'),
            preserve_default=False,
        ),
    ]
