# Generated by Django 3.0.4 on 2020-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0019_sucursal_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True),
        ),
    ]
