# Generated by Django 3.0.4 on 2020-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_pedido_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
